### PR TITLE
feat: add Inertia.js in frameworks

### PR DESCRIPTION
**Pull request by KABBOUCHI**
Adds [Inertia.js](https://inertiajs.com) as a detectable framework

## Types of changes

- [x] New Detector
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Adding a new detector for the Inertia.js framework, similar to `vuepress` it can be detectable by checking `__vue__.$inertia`

Inertia.js Vue Example : https://demo.inertiajs.com/login
## Checklist:

- [x] I have updated the README accordingly 
- [x] I have added the icon of my detector in `icons/`

### CODE REVIEW

**Comment by web2033** [comment]
They even don't call themselves a "framework"

**Comment by KABBOUCHI** [comment]
@web2033 its very close to a framework, its surely needs backend (`laravel`) & frontend lib (`vuejs`) to work properly.

You can compare it to `nuxt.js`, `nuxt.js` needs `nodejs` (server/ssr) and `vue` (front). 

If you think it fit better in other category please share your opinion.

**Comment by Atinux** [comment]
For my POV it is fine being listed as Framework on Vue Telemetry.

Nice PR :)

**Comment by web2033** [comment]
Hey, @Atinux can you tell us who's behind the design for Vue Telemetry and other Nuxt projects?

**Comment by Atinux** [comment]
Actually, I moved Inertia to plugins finally, since you use it as a Vue plugin: https://inertiajs.com/client-side-setup

**Pull request merged**
